modules/Output/Routes/web.php
<?php

use Modules\Output\Entities\Output;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' => 'dashboard', 'middleware' => 'auth:dashboard'], function(){

    // rest of routes
    Route::group(['prefix' => 'outputs', 'as' => 'output.'], function(){

        //the grouped operations (declare them before resource routes to avoid conflicts)
        Route::delete('delete-many', [Modules\Output\Http\Controllers\OutputController::class, 'destroyMany'])
        ->name('destroy.many')
        ->middleware('can:output.actions.delete');

        Route::get('ajax/datatable', OutputDatatableController::class)
            ->name('datatable')
            ->middleware('can:output.actions.view');

        //Model Resources routes
        //didn't use resource to have the ability to attach permission middleware to each route
        // avoid using middlewares inside of controllers keep this structure maintained
        Route::get('/',[Modules\Output\Http\Controllers\OutputController::class, 'index'])
            ->name('index')
            ->middleware('can:output.actions.view');

        Route::post('/',[Modules\Output\Http\Controllers\OutputController::class, 'store'])
            ->name('store')
            ->middleware('can:output.actions.add');

        Route::get('create',[Modules\Output\Http\Controllers\OutputController::class, 'create'])
            ->name('create')
            ->middleware('can:timer.actions.add');

        Route::put('{output}',[Modules\Output\Http\Controllers\OutputController::class, 'update'])
            ->name('update')
            ->middleware('can:timer.actions.edit');

        Route::get('{output}/edit',[Modules\Output\Http\Controllers\OutputController::class, 'edit'])
            ->name('edit')
            ->middleware('can:timer.actions.edit');

        Route::delete('{output}',[Modules\Output\Http\Controllers\OutputController::class, 'destroy'])
            ->name('delete')
            ->middleware('can:timer.actions.delete');



            
        Route::post('/status/update',[Modules\Output\Http\Controllers\OutputController::class, 'update_status'])
        ->name('status.update');


    });




    
    // rest of routes timer
    Route::group(['prefix' => 'timers', 'as' => 'timer.'], function(){

        //the grouped operations (declare them before resource routes to avoid conflicts)
        Route::delete('delete-many', [Modules\Output\Http\Controllers\TimerController::class, 'destroyMany'])
        ->name('destroy.many')
        ->middleware('can:timer.actions.delete');

        Route::get('ajax/datatable', TimerDatatableController::class)
            ->name('datatable')
            ->middleware('can:timer.actions.view');

        //Model Resources routes
        //didn't use resource to have the ability to attach permission middleware to each route
        // avoid using middlewares inside of controllers keep this structure maintained
        Route::get('/',[Modules\Output\Http\Controllers\TimerController::class, 'index'])
            ->name('index')
            ->middleware('can:timer.actions.view');

        Route::post('/',[Modules\Output\Http\Controllers\TimerController::class, 'store'])
            ->name('store')
            ->middleware('can:timer.actions.add');

        Route::get('create',[Modules\Output\Http\Controllers\TimerController::class, 'create'])
            ->name('create')
            ->middleware('can:timer.actions.add');

        Route::put('{timer}',[Modules\Output\Http\Controllers\TimerController::class, 'update'])
            ->name('update')
            ->middleware('can:timer.actions.edit');

        Route::get('{timer}/edit',[Modules\Output\Http\Controllers\TimerController::class, 'edit'])
            ->name('edit')
            ->middleware('can:timer.actions.edit');

        Route::delete('{timer}',[Modules\Output\Http\Controllers\TimerController::class, 'destroy'])
            ->name('delete')
            ->middleware('can:timer.actions.delete');


    });

});


route::get('/test',function(){

return date('m');

});

modules/Output/Resources/views/dashboard/index.blade.php
@extends('dashboard::layout.main')

@section('pageHead')
<title>{{ __('output::header.title') }} | Sengine</title>
<meta name="description"
content="put description here" />
<meta name="keywords"
content="put key words here" />
@endsection

@section('pageStyle')
<link href="{{ asset('/themes/metro8/assets/plugins/datatables/datatables.bundle.css') }}" rel="stylesheet"
    type="text/css">
@endsection

@section('page_title')
<!--begin::Page title-->
<div data-kt-swapper="true" data-kt-swapper-mode="prepend"
    data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_header_nav'}"
    class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
    <!--begin::Title-->
    <h1 class="d-flex align-items-center fw-bolder fs-3 my-1 toolbar-main-title-color">{{ __('output::header.title') }}</h1>
    <!--end::Title-->
</div>
<!--end::Page title-->
@endsection

@section('content')
<div class="post d-flex flex-column-fluid" id="kt_post">
    <!--begin::Container-->
    <div id="kt_content_container" class="container-xxl container-full-width">
        <!--begin::Card-->
        <div class="card">
            <!--begin::Card header-->
            <div id="header-container" class="card-header border-0 pt-6">
                <x-dashboard::dt-search dt-target="_datatable"/>
                <!--begin::Card toolbar-->
                <x-dashboard::dt-toolbar>
              
                    @can('output.actions.export')
                    <!--begin::Export-->
                    <x-dashboard::dt-export dt-target="_datatable"/>
                    <!--end::Export-->
                    @endcan

                    <!--begin::ColumnFilter-->
                    <x-dashboard::dt-col-filter dt-target="_datatable"/>
                    <!--end::ColumnFilter-->

                    <!--begin::Refresh-->
                    <x-dashboard::dt-refresh dt-target="_datatable"/>
                    <!--end::Refresh-->

                    <!--begin::FullScrn-->
                    <x-dashboard::dt-full-scrn dt-target="_datatable"/>
                    <!--end::FullScrn-->

                    <!--begin::Group actions-->
                    <x-slot name="group">
                        <!--begin::Input group-->
                        <x-dashboard::dt-actn-grp>
                            @can('output.actions.delete')
                            <x-dashboard::dt-actn-grp-delete data-action-url="{{ route('output.destroy.many') }}" />
                            @endcan
                        </x-dashboard::dt-actn-grp>
                        <!--end::Input group-->
                      
                        
                    </x-slot>
                    <!--end::Group actions-->
                </x-dashboard::dt-toolbar>
                <!--end::Card toolbar-->
            </div>
            <!--end::Card header-->
            <!--begin::Card body-->
            <div class="card-body pt-0">
                <!--begin::Table-->
                <x-dashboard::data-table id="_datatable" data-url="{{ route('output.datatable') }}" 
                    data-order='[[ 1, "desc" ]]' data-page-length='25'>

                    
                    <th>
                        {{ __('output::datatable.columns.name') }}
                    </th>

                    <th>
                        {{ __('output::datatable.columns.device') }}
                    </th>

                

                    <th>
                        {{ __('output::datatable.columns.state') }}
                    </th>

                    <th>
                        {{ __('output::datatable.columns.creation_date') }}
                    </th>

                    
                    <th class="min-w-70px action-buttons" can-toggle="false" can-print="false" style="width: 150px;">
                        {{ __('core::global.datatable.columns.actions') }}
                    </th>
                    
                </x-dashboard::data-table>
                <!--end::Table-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
</div>
@endsection


@section('extras')
<!--begin::Scrolltop-->
@include('dashboard::layout.partials.scrollup')
<!--end::Scrolltop-->
<x-dashboard::dt-modal/>
@endsection

@section('pageScripts')

<script src="{{asset('/themes/metro8/assets/plugins/datatables/datatables.bundle.js')}}"></script>
<script src="{{asset('/themes/metro8/assets/js/bundle/datatable.js')}}"></script>
<script src="{{asset('/themes/metro8/assets/js/bundle/modal_form_validation.js')}}"></script>
<script src="{{asset('/themes/metro8/assets/modules/output/js/output.js')}}"></script>

<script src="{{asset('/themes/metro8/assets/js/bundle/dt_media_query.js')}}"></script>


@endsection